baseurl = "https://im5tu.io/"

title = "Stuart Blackler's Blog"
languageCode = "en-us"
theme = "bones"
metaDataFormat = "json"
enableRobotsTXT = true
pygmentsuseclasses = true

[permalinks]
  article = "article/:year/:month/:title/"

[params]
  description = "I am a highly experienced lead software engineer, architect & proponent of clean coding. Currently, I am helping to disrupt the banking sector by building high quality micro-services & APIs. This includes looking at some of the latest technologies and architectural patterns & evaluating them for use in various business scenarios. I am also contributing to the future of the finance sector by working with the International Standards Organisation & its corresponding mirror groups in the British Standards Institute, on financial services APIs. Follow my journey via the channels below:"
  name = "Stuart Blackler"
  jobTitle = "Lead Architect / Software Consultant / Crossfitter"