baseurl = "https://im5tu.io/"
title = "Stuart Blackler's Blog"
languageCode = "en-us"
theme = "hello-friend-ng"
metaDataFormat = "json"
enableRobotsTXT = true
pygmentsuseclasses = true
ignorefiles = [ "content/draft/.*" ]

[Author]
  name = "Stuart Blackler"

[permalinks]
  article = "article/:year/:month/:title/"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  
  # Subtitle for home
  homeSubtitle = "I'm Stu, welcome to my online home :)"

  # Logo
  [params.Logo]
    logoText = "im5tu.io"

  # Social icons
  [params.portrait]
    path = "/img/profile.jpg"
    alt = "Portrait"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/im5tu"

  [[params.social]]
    name = "github"
    url  = "https://github.com/im5tu"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/im5tu/"

  [[params.social]]
    name = "youtube"
    url  = "https://www.youtube.com/channel/UCF5dh7bm49bpsZjWHYDG4Lg"

[markup]
  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter as it conflicts with Academic's highligher.

[minify]
  minifyOutput = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[menu]
  [[menu.main]]
    identifier = "articles"
    name       = "Articles"
    url        = "article/"

  [[menu.main]]
    identifier = "rss"
    name       = "RSS Feed"
    url        = "/index.xml"

  [[menu.main]]
    identifier = "twitter"
    name       = "Twitter"
    url        = "https://twitter.com/im5tu"
    
  [[menu.main]]
    identifier = "youtube"
    name       = "YouTube"
    url        = "https://www.youtube.com/channel/UCF5dh7bm49bpsZjWHYDG4Lg"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "RSS"]