baseurl = "https://im5tu.io/"

title = "Stuart Blackler's Blog"
languageCode = "en-us"
theme = "hugo-bones"
metaDataFormat = "json"
enableRobotsTXT = true
pygmentsuseclasses = true

[permalinks]
  article = "article/:year/:month/:title/"

[params]
  description = "I am an experienced, highly motivated and hard working software engineer currently developing innovative solutions for a varity of high profile clients. When I am not developing, I inspire others to augment their intrinsic beliefs, realise their dreams & lead a life of abundance. Follow my journey via the channels below:"
  name = "Stuart Blackler"
  jobTitle = "Software Developer / Mentor / Health Enthusiast"