baseurl = "https://im5tu.io/"

title = "Stuart Blackler's Blog"
languageCode = "en-us"
theme = "bones"
metaDataFormat = "json"
enableRobotsTXT = true
pygmentsuseclasses = true

[permalinks]
  article = "article/:year/:month/:title/"

[params]
  name = "@im5tu"
  jobTitle = "Stuart Blackler"

[markup]
  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter as it conflicts with Academic's highligher.