baseurl = "https://im5tu.io/"

title = "Stuart Blackler's Blog"
languageCode = "en-us"
theme = "hugo-bones"
metaDataFormat = "json"
enableRobotsTXT = true
pygmentsuseclasses = true

[permalinks]
  article = "article/:year/:month/:title/"