baseurl = "https://im5tu.io/"

title = "Stuart Blackler's Blog"
languageCode = "en-us"
theme = "bones"
metaDataFormat = "json"
enableRobotsTXT = true
pygmentsuseclasses = true

[permalinks]
  article = "article/:year/:month/:title/"

[params]
  description = "I am a lead architect at the UK's first clearing bank in 250 years, ClearBank. I specialise in designing and building backend systems, specifically messaging based systems and RESTful API's. I am also one of two UK representives in an ISO working group looking at API's in financial services. Follow my journey via the channels below:"
  name = "Stuart Blackler"
  jobTitle = "Lead Architect / Software Consultant / Crossfitter"